package.json
src/components/common/carousel.tsx
yarn.lock

[Next 13 문서](https://nextjs.org/blog/next-13)
[React-hook-form 문서](https://react-hook-form.com/get-started/)
[swiper 문서](https://swiperjs.com/get-started)
- 예시로 carousel 컴포넌트에 샘플 코드 추가했습니다. 이후 실제 디자인에 맞춰 수정해야할듯합니다.
X
- ⛔️
```
"next": "^13.0.2",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"eslint-config-next": "^13.0.2",
```
```
"react-hook-form": "^7.39.1",
"swiper": "^8.4.4",
```
- ⛔️

chore: Next 13 적용, React-hook-form, swiper 디펜던시 추가

---

.eslintrc
next.config.js
package.json
src/components/common/BottomSheet.tsx
src/components/common/BottomSheetOptions.tsx
src/components/common/Button.stories.tsx
src/components/common/Button.tsx
src/components/common/Portal.tsx
src/hooks/useBottomSheet.ts
src/pages/_app.tsx
src/pages/playground.tsx
src/store/bottomSheet.ts
src/store/components/atoms.ts
src/store/components/index.ts
yarn.lock

- Portal 을 사용해서, Bottomsheet 컴포넌트가 열리게 합니다. 
- 이후 popup 컴포넌트에도 사용할 수 있을것 같습니다.
- Portal 컴포넌트로 감싸고, isShowing boolean 값으로 컨트롤합니다.
```
<Portal isShowing={isShowing}>
<ChildrenComponent />
</Portal>
```
- bottom sheet 바텀시트 컴포넌트 추가
- bottomsheet 내부에 들어가는 optionlist 컴포넌트 추가
- styled-components 를 사용 시에 next dev 의 HMR 정상 동작하지 않는 이슈가 있어서 next.config.js 수정
- ⛔️
```
"@types/styled-components": "^5.1.26",
```
- ⛔️

Feat: bottom sheet 컴포넌트

---

.storybook/main.js
package.json
yarn.lock

- svg import 버그 해결
#38 
- storybook webpack 설정에 svgr 이 되어있지 않아, 계속 svg를 사용하는 컴포넌트를 storybook에 import 시 에러가 발생했습니다. 
참고: https://github.com/storybookjs/storybook/issues/9070
```
"@svgr/webpack": "^6.5.1",
```
- ⛔️

:bug: fix: storybook svg import error

---

.storybook/main.js
src/components/common/CheckBox.stories.tsx
src/components/common/CheckBox.tsx
src/components/common/icons/Check.tsx
src/components/common/icons/index.ts
src/lib/utils.ts

- 체크박스 컴포넌트 추가
- storybook에서 Next.js module 파일 경로를 찾아오지 못하는 이슈가 있어 해결했습니다. [참고](https://github.com/storybookjs/storybook/issues/11639)
- ⛔️
- ⛔️
- ⛔️

:sparkles: checkbox component

---

module.d.ts
src/components/common/RadioGroup.tsx
src/constants/styles/index.ts
src/hooks/useBottomSheet.ts
src/hooks/useRadioGroup.ts
src/pages/playground.tsx

사용 시 useRadioButton 을 다음과 같이 사용해서 컴포넌트에 연결합니다.
```
const { list, currentSelected, onChange } = useRadioGroup([
{
key: 'INCORRECT',
label: '사용자 정보가 부정확해요.',
},
{
key: 'MARKETING',
label: '광고성/홍보성 글이에요.',
},
{
key: 'DUPLICATED',
label: '이 게시글이 도배 되어있어요.',
},
]);
<RadioGroup list={list} currentSelected={currentSelected} onChange={onChange} />
```
list: 라디오 버튼에 들어가는 key, label로 이루어진 리스트
currentSelected: 선택된 라디오 값 
이후 DB에 저장할때 key값이 사용될것 같아 라벨에 해당하는 key를 따로 가지고있는 형태로 작업하였습니다.
- tailwind 사용하면서 작업 속도가 너무 안나서 ㅠㅠ styled-components 사용하였습니다.
- ⛔️
- ⛔️

Feat: radio button 

---

.commitlintrc.js
.storybook/webpack.config.js
src/components/common/RadioGroup.tsx

- svg 가 import 안되는 이슈가 있어서 확인해보니 webpack 에 svgr 세팅이 안되어있어서 추가했습니다.
- commitlint config에 `WIP` 를 입력 시에는 commit lint를 통과하는 옵션을 추가합니다. 
- ⛔️
- ⛔️
- ⛔️

Fix: webpack svgr 세팅, commitlint config 수정

---

src/components/common/SelectInput.stories.tsx
src/components/common/SelectInput.tsx
src/components/common/TextInput.stories.tsx
src/components/common/TextInput.tsx
src/components/common/TextSelectInput.stories.tsx
src/components/common/TextSelectInput.tsx
src/components/icons/RightArrowIcon.tsx

```diff
+ selectedInputList?: string[];
+ href: string;
```
- `InputList`를 받아 `placeholder`에 보여줍니다. ( 데이터 형태는 추후 수정될 수 있습니다. )
- `href`를 통해 선택 이후 원하는 페이지로 이동합니다.
- `title`, `explanation`, `required`등을 설정할 수 있습니다.
- 기존 구조에서 공통으로 사용 가능한 컴포넌트로 변경하였습니다.
- #57 
- ⛔️
- ⛔️

feat: talent select input

---

src/components/common/HeaderTitle.tsx
src/components/talentRegister/TalentRegisterHeader.tsx

- color 적용이 제대로 이루어지지 않아 style을 변경하였습니다.
- 바뀐 디자인에 따라 변경이 필요합니다. 현재 디자인상 이미지파일로 되어있어 추후 논의 이후 변경이 필요합니다. 
- #63 
- ⛔️
- ⛔️

fix: talent register header

---

.storybook/preview.js
src/components/common/Card.stories.tsx
src/components/common/HeaderTitle.stories.tsx
src/components/common/NavigationBar.stories.tsx
src/components/talentRegister/TalentRegisterFormOne.stories.tsx
src/components/talentRegister/TalentRegisterFormThree.stories.tsx
src/components/talentRegister/TalentRegisterFormTwo.stories.tsx
src/components/talentRegister/TalentRegisterHeader.stories.tsx
src/components/talentRegister/TalentRegisterHeader.tsx
src/components/talentRegister/TalentRegisterTextRadioButtonGroup.stories.tsx
src/components/talentRegister/TalentRegisterTextRadioButtonGroup.tsx
src/pages/Home.stories.tsx
src/pages/profile/Profile.stories.tsx
src/pages/talent/register/exchange/index.tsx
src/pages/talent/register/share/index.tsx

- storybook `preview.js` 에 관련 옵션을 추가했어요.
- 아래와 같은 대분류로 `story`를 분류했어요.
```diff
// 현재 스토리북 폴더 분류 
+ Commons
+ Components
+ Pages
```
- 만들어진 페이지에 대한 `story`를 모두 추가했어요.
- 재능 등록과 관련된 모든 `story`를 추가했어요.
```diff
// Page
+ Home 
+ Profile 
// Components
+ TalentRegisterForm
+ TalentRegisterTextRadioButtonGroup
+ TalentRegisterHeader
```
- #83 
- ⛔️
- ⛔️

feat: storybook

---

src/apis/index.ts
src/components/common/ClickTag.tsx
src/components/common/ClickTagList.tsx
src/components/common/SelectInput.tsx
src/components/common/Tag.tsx
src/components/common/TextSelectInput.tsx
src/components/talentRegister/TalentRegisterCategoryBottomSheet.tsx
src/components/talentRegister/TalentRegisterCategoryTabList.tsx
src/components/talentRegister/TalentRegisterCategoryTagList.tsx
src/components/talentRegister/TalentRegisterFormOne.tsx
src/components/talentRegister/TalentRegisterFormThree.tsx
src/components/talentRegister/TalentRegisterFormTwo.tsx
src/hooks/useRegisterTalentPost.ts
src/hooks/useTab.ts
src/lib/types.ts
src/lib/utils.ts
src/pages/talent/register/exchange/category/index.tsx
src/pages/talent/register/share/category/index.tsx
src/store/components/atoms.ts
src/store/components/selectors.ts
src/store/components/types.ts
src/typings/common.d.ts

- 기존 `Tag` 컴포넌트에서 `click` 로직을 분리하기 위해 새로운 컴포넌트를 만들었어요.
- `delete` 아이콘이 추가되었어요.
| ClickTag | ClickTag (delete) |
|---|---|
| <img width="244" alt="image" src="https://user-images.githubusercontent.com/79739512/208225397-262ab62c-4440-4f62-9bad-4164b5356df8.png"> | <img width="205" alt="image" src="https://user-images.githubusercontent.com/79739512/208225425-5163cfe8-edc0-48e0-91e3-b39f4ba1a491.png"> |
- 재능 등록 카테고리 선택시 아래 나오는 바텀 시트를 추가했어요.
- 동적으로 만들어진 `atom`에 접근하기 위한 `key atom`들을 추가했어요.
- 재능 등록에 필요한 `body object`를 만드는 `selector`를 추가했어요.
- `useTab`에서 상태 관리 로직을 `hook` 내부에 작성하면서 `key` 관리가 어려워졌어요.
- 추후에 `useTab` 로직을 `recoil` 로직으로 옮기는 과정이 필요해요. 
```javascript
// TODO: 수동으로 받고 있는 tabKeyAtom을 동적으로 변경하는 코드가 필요합니다.
const tabKeyAtom = atom<string[]>({
key: 'talentRegisterInputKey',
default: …
```

feat: talent register category 2

---

.storybook/main.js
.storybook/preview.js
package.json
src/components/common/SelectInput.stories.tsx
src/components/common/TextSelectInput.stories.tsx
src/components/pages/Profile.stories.tsx
src/components/pages/TalentRegister.stories.tsx
src/components/pages/TalentRegisterExchange.stories.tsx
src/components/pages/TalentRegisterExchangeCategory.stories.tsx
src/components/pages/TalentRegisterShare.stories.tsx
src/components/pages/TalentRegisterShareCategory.stories.tsx
src/components/talentRegister/TalentRegisterHeader.stories.tsx
src/pages/playground.tsx
src/pages/profile/index.tsx
yarn.lock

- `deprecated`된 `asset` 사용 방법에서 권장되는 방법으로 변경했어요. 
- 기존 방법 사용시 `build`된 `storybook` 폴더에 `asset` 폴더가 생성되지 않는 오류를 발견했어요.
- 권장되는 방법으로 변경하여 오류를 해결했어요. 
- 이미지 `src`를 `build`된 `storybook` 폴더 기준으로 변경했어요. 
- `Next` 프로젝트 내에서 `image src`로 사용되던 절대경로 때문에 오류가 발생했어요.
- `build`되는 `storybook` 폴더 기준으로 경로를 변경하여 오류를 해결했어요.
```diff
// package.json
- "storybook": "start-storybook -p 6006 -s ./public",
- "build-storybook": "build-storybook s public",
+ "storybook": "start-storybook -p 6006",
+ "build-storybook": "build-storybook",
// .storybook/main.js
+ staticDirs: ['../public'],
```
```diff
+ "storybook-addon-next": "1.7.1"
```
- 기존 `string[]` 에서 `{ id: number; name: string; }[]` 와 같이 `type`을 변경했어요.
- 해당 부분 때문에 `CD` 과정에서 오류가 발생했어요.
```diff
-  selectedInputList: ['액세서리/패션소품', '업무 자동화', '프론트엔드', '제2의 장벽'],
+ …
```

bug: storybook

---

next.config.js
src/apis/index.ts

- axios 에서 baseURL이 잘못 설정되어 proxy로 정상적으로 rewrites 되지 않던 이슈 해결
```
localhost:3000  -> dev-be.ping-pong.world 로 redirect
```
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Fix using wrong baseurl at axios

---

next.config.js
src/hooks/queries/useCategoriesQuery.ts
src/hooks/queries/useCustomPostsQuery.ts
src/hooks/queries/useInfinitePostsQuery.ts
src/hooks/queries/usePostLikeMutate.ts
src/hooks/queries/usePostQuery.ts
src/hooks/queries/usePostUnlikeMutate.ts
src/hooks/queries/useUserInfoQuery.ts
src/hooks/useGetCategory.ts

- next.config.js 의 rewrites에 `/api/vi` 추가하고 호출부의 url에서는 모두 삭제
- NEXT_PUBLIC_SERVER_URL 은 next.config에 rewrites 에서 https:// prefix 붙이기를 권장하여 변경하지 않았습니다.
.env.development
```
NEXT_PUBLIC_SERVER_URL="dev-be.ping-pong.world"
```
.env.production
```
NEXT_PUBLIC_SERVER_URL="be.ping-pong.world"
```
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Add /api/v1 to next config

---

next.config.js
src/hooks/queries/useCategoriesQuery.ts
src/hooks/queries/useCustomPostsQuery.ts
src/hooks/queries/useInfinitePostsQuery.ts
src/hooks/queries/usePostLikeMutate.ts
src/hooks/queries/usePostQuery.ts
src/hooks/queries/usePostUnlikeMutate.ts
src/hooks/queries/useUserInfoQuery.ts
src/pages/posts/[id].tsx

localhost 뒤의 path 전체가 rewrites 되어 
localhost/posts/8 이 dynamic route인 `posts/[id].tsx` 라우터로 접근되지 않고 실제 `/posts/8` API 로 접근되어 json이 표시됨. 
api 호출하는 부분에 `/.api` 붙여서 해결
-> 이후 api 연결 시 `/.api` prefix를 붙여서 사용해야합니다. 
@L2HYUNN @hwangyena 
- 게시글 상세 페이지 접근 시 api response json 나오는 이슈
- ⛔️
- ⛔️

Fix: 게시글 상세 페이지 안나오는 이슈

---

src/components/posts/PostHeader.tsx
src/components/posts/PostHeaderNav.tsx
src/pages/posts/[id].tsx
src/pages/profile/index.tsx

-> 게시글 상세 이동 후 query로 파악해서 아래UI가 분기처리가 됩니다. 
내가쓴글: '게시물 삭제' 표시
다른사람글: '신고하기' 표시
내가쓴글: 프로필 보기 버튼 미노출
다른사람글: 프로필 보기 노출
- ⛔️
- ⛔️
- ⛔️

feat: 프로필 페이지에서 내가쓴글 포스트 확인용 isMyPost query 추가

---

src/components/common/Popup.tsx
src/components/posts/PostReportRadioGroup.tsx
src/components/setting/DeleteAccountRadioGroup.tsx
src/hooks/queries/useDeleteAccountMutate.ts
src/pages/posts/[id].tsx
src/pages/setting/index.tsx

탈퇴하기 API 연결
- DeleteAccountRadioGroup
- useDeleteAccountMutate 추가
신고하기, 탈퇴하기 API 팝업
- default 값 선택되어있도록 initialValue 추가
- title, content 스타일 디자인에 맞추어 수정
- ⛔️
- ⛔️
- ⛔️

Feat: 탈퇴하기 API 연결

---

src/hooks/queries/useDeleteAccountMutate.ts
src/hooks/queries/useReportPostMutate.ts
src/pages/posts/[id].tsx

신고하기, 탈퇴하기 
- 성공, 에러에 따라서 toast 메세지 노출
오픈채팅 링크
- a link로 바로 이동되지 않고 컨펌 모달 노출 후 확인 시 이동
- ⛔️
- ⛔️
- ⛔️

Fix: 신고하기 탈퇴하기 토스트 메세지, 오픈채팅 이동 컨펌창 노출

---

src/components/profile/ProfileCategoryTagList.tsx
src/components/talentRegister/TalentRegisterCategoryTabList.tsx
src/components/talentRegister/TalentRegisterCategoryTagList.tsx
src/components/talentRegister/TalentRegisterFormThree.tsx
src/pages/talent/register/exchange/category/index.tsx
src/pages/talent/register/share/category/index.tsx

재능등록 쪽 탭을 담고 있는 container div에 position: fixed 가 들어가있어서 발생한 문제로 보입니다
position:fixed 삭제하고, 삭제하고나니 padding 이 전부 수정되어야해서 Form, Tab, TagList 쪽 패딩 마진 수정하였습니다.
- ⛔️
- ⛔️
- ⛔️

:bug: fix: 재능등록 탭 가로 스크롤 되지 않는 이슈 해결

---

src/components/common/Layout.tsx
src/pages/main.tsx
src/pages/profile/index.tsx

- userInfoQuery 호출, myInfo recoil 에 저장하는 로직을 Layout으로 이동합니다. 
- 프로필보기에서 새로고침시 데이터 없어서 화면이 보이지 않는 이슈를 해결합니다.
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Move userInfoQuery to Layout

---

src/pages/main.tsx

- `activeCategoryList.length` 조건 때문에 길이가 0 일때 0이 `return` 되는 문제를 해결했어요
- ⛔️
- ⛔️
- ⛔️

fix: Fix activeMidCategoryList condition error

---

package.json
yarn.lock

쿠키 인증 문제로 `localhost` 사용시 `dev` 서버를 이용할 수 없습니다.
따라서 `local` 환경에서 `dev` 서버 사용을 위해 다음과 같은 설정이 필요합니다.
`hostFile` 내용 변경 ( 중요 )
`127.0.0.1: localhost` -> `127.0.0.1: local-fe.ping-pong.world`로 호스트네임 변경이 필요합니다. 
관련 Tool 사용하시거나 스크립트 파일 수정 하시면 됩니다!
```
// 스크립트 파일 수정시
sudo vim /private/etc/hosts
```
```
// 위의 설정을 마친 후
yarn proxy
yarn dev 
```
1. 이미 열려있는 포트로 인해 실행이 안 될 수 있습니다.
```
lsof -i:443
lsof -i:3000
kill -9 <PID>
```
- ⛔️
- ⛔️
- ⛔️

chor: Add local-ssl-proxy

---

src/pages/nickname.tsx

- `nickname` 변경 이후 `main` 페이지로 이동할때 기존 `API` 내용이 캐쉬 처리 되어 반영되지 않는 문제를 해결했어요. 
- 처음 `Layout`에서 호출된 `user` 정보가 캐쉬처리되어 발생한 문제로 보여요! 
- 쿼리 무효화를 통해 해당 문제를 해결했어요.
```
닉네임 변경 이후 `network` 탭을 통해 데이터를 다시 받아오는 것을 확인했어요! 
// 요청에서 nickname 이후 요청을 확인해주세요 :) 
```
|적용 전 |적용 후 |
|---|---|
|![스크린샷 2023-01-08 오후 4 26 35](https://user-images.githubusercontent.com/79739512/211185501-23b1a41e-0081-45e2-8433-d91fb2c806ac.png)|![스크린샷 2023-01-08 오후 4 34 10](https://user-images.githubusercontent.com/79739512/211185503-4fe19ab5-fcb7-4abd-b5a8-83a3ec6e286e.png) |
- ⛔️
- ⛔️
- ⛔️

fix: Fix nickname not changed error

---

src/components/common/Layout.tsx

```html
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0" />
```
- ⛔️
- ⛔️
- ⛔️

fix: Add meta data to prevent zoom

---

src/components/common/CardCarousel.tsx
src/hooks/queries/useCustomPostsQuery.ts
src/pages/main.tsx

- 맞춤 재능 조회시 subCategory를 1로 고정해두고 호출 [QA 이슈 링크](https://www.notion.so/depromeet/subCategory-1-3b15325571b64c1c896022918348a07d)
- 맞춤 재능 카드 클릭시 이동하지 않음
- ⛔️
- ⛔️
- ⛔️

Fix: 메인페이지 맞춤 재능

---

src/components/common/CardCarousel.tsx

Link 로 감쌌더니 디자인 깨지는 이슈가 있어서 수정 
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Fix card design width full

---

src/components/common/CardCarousel.tsx

- 명세서에 있는 `postId`로 연결되어야 하는데 id로 연결되어 오류가 발생했어요.
- 커스텀 포스트와 일반 포스트 `response` 값이 다른거 같아 새로운 타이핑 방식이 필요해보여요
- ⛔️
- ⛔️
- ⛔️

fix: Fix custom post routing issue

---

src/pages/posts/[id].tsx

- 처음 게시글 삭제 이후 `bottomSheetActiveOptionAtom`에 `Delete`가 보존되어 문제가 발생했어요.
- `mutate` 요청이후 해당 상태를 초기화하게 로직을 추가했어요.
- 처음 게시글 생성 이후 게시글을 삭제할 때 `router.back()`으로 인해 다시 게시글 등록으로 돌아가는 문제가 발생했어요.
- `router.query.new`로 체크하는 조건을 추가해 문제를 해결했어요. 
- ⛔️
- ⛔️
- ⛔️

fix: Fix post remove action error

---

src/components/profile/ProfileView.tsx
src/pages/profile/index.tsx

- 아래와 같이 프로필 화면에서 뒤로가기시 편집화면에서 나오는 팝업이 나오는 오류가 발생했어요.
- `usePopupWithBlock(undefined)`를 이용하여 프로필 화면에서 해당 팝업이 나오지 않게 문제를 해결했어요.
- ⛔️
- ⛔️
- ⛔️

fix: Fix profile edit, profile index popup issue

---

src/components/common/Header.tsx
src/components/common/Input.stories.tsx
src/components/common/Input.tsx
src/components/common/TextInput.tsx
src/components/styles/index.tsx
src/hooks/useAuth.ts
src/hooks/useNickname.ts
src/lib/utils.ts
src/pages/nickname.tsx
src/pages/posts/[id].tsx
src/pages/profile/edit.tsx
src/typings/common.d.ts

- 하단버튼에 게시물 상세 가려지는 이슈 해결
- 게시물 상세 Divider 변경
- 닉네임에 특수문자, 숫자 입력 시 에러메세지(한글,영어,공백 허용)
- 에러메세지 있을 경우 저장 버튼 비활성화
- 글자 길이 맞지 않을경우 에러메세지 노출
- Input 이 받는 onChange props 가 event handler로 변경되었습니다.
- 사용되는 함수들 전부 변경완료 
- ⛔️
- ⛔️
- ⛔️

Fix: 닉네임 에러 메세지 노출

---

src/components/common/ClickTag.tsx
src/components/main/SubCategoryFilter.tsx
src/components/profile/ProfileCategoryTagList.tsx
src/components/talentRegister/TalentRegisterCategoryTagList.tsx
src/hooks/useTab.ts
src/hooks/useTag.ts
src/pages/main.tsx
src/store/components/atoms.ts

- 아래 이슈들을 해결하기 위해 리팩토링 + 버그 수정
- tabAtomFamily 와 categoryTab 로직을 분리하여 사용하기 위해 별도의 atom을 생성했습니다. 
- 기존에 등록 카테고리 화면에서 동일 화면에서 tabAtomFamily가 tagList와 selectedTab 에 동시에 사용되어 id of undefined 이슈가 발생한것으로 보입니다. 
- selectedTab 의 기본 값을 array -> object 로 수정하면서, activeMidCategoryId selector가 정상적으로 동작하고, 소분류 bottomSheet 가 초기화 됩니다. 
- 탭 두번 클릭시 id undefined 이슈
- 탭 선택시 선택 해제됨 이슈
- 중분류 선택이 바뀌어도 소분류 bottomSheet 초기화 안됨 이슈
- ⛔️
- ⛔️

Fix: tab list 이슈 수정

---

src/components/common/TextBox.tsx

링크 부분 수정
- textbox disabled일때 디자인 변경
- ⛔️
- ⛔️
- ⛔️

Redesign: 프로필 text box
