.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/pr-labeler-config.yml
.github/workflow/pr-labeler.yml

- PR template 추가
- 항상 변동이 있지 않은 부분에 대해서는 X 이모지를 기본으로 추가해놓았습니다. 해당 항목에 변동이 있을때는 수정하여 올리면 될것같습니다. 
- PR labeler 추가
- 브랜치 명에 따라 PR 라벨링 해주는 workflow를 추가합니다.
- enhancement, refactor, bug, design, chore - 라벨 추가
- CodeOwners 추가 
- 자동으로 reviewer 지정을 위해서 codeowners를 추가합니다.
- ⛔️
- ⛔️
- ⛔️

feature: PR template, PR labeler 추가

---

.github/pr-labeler-config.yml

- pr-labeler comma 삭제 - 내부에 있는 comma 때문에 에러 발생
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Remove comma at prlabeler.yml

---

.vscode/css_custom_data.json
.vscode/settings.json
package.json
postcss.config.js
src/pages/_app.tsx
yarn.lock

tailwind 설정을 위한 파일 추가
- #16  
```
"autoprefixer": "10.4.13",
"postcss": "8.4.18",
```
- ⛔️

📦 chore: tailwind configuration

---

next.config.js
src/hooks/useCategorySelection.tsx

카테고리 선택 훅을 추가합니다.
- #14 
- ⛔️
- ⛔️

✨ feature: add category selection hook

---

.github/workflows/chromatic.yml

- dev 에 머지하지 않고 chromatic action 테스트를 위해 test 브랜치를 yml에 추가합니다.
- ⛔️
- ⛔️
- ⛔️
- ⛔️

chore: Add test branch to chromatic

---

.gitignore
.storybook/main.js
.storybook/preview.js
package.json
public/icons/arrow-left.svg
public/icons/arrow-right.svg
src/components/common/Button.stories.tsx
src/components/common/Button.tsx
yarn.lock

- storybook 에서 tailwind 정상동작하도록 `@storybook/addon-postcss` 추가
- preview.js 에 globals.css 추가
- button 컴포넌트는 tailwind적용 확인용으로 만든거여서 내부 코드는 이후 수정 예정입니다
``` 
"tailwindcss": "^3.2.4",
"@storybook/addon-postcss": "^2.0.0",
"postcss-loader": "^7.0.1",
```
postcss-loader 는 이후 webpack으로 storybook 빌드할때 쓰일것같은데, 버그 수정 테스트하다가 설치했습니다..
- ⛔️

Fix: storybook에서 tailwind 적용

---

src/apis/index.ts
src/hooks/test.ts
src/lib/utils.ts
src/pages/_app.tsx
src/pages/index.tsx

- useQuery, useMutation 함수를 조금 변경했습니다. 혹시 수정 원하시는 부분이 있으면 자유롭게 코멘트 부탁드립니당!
- ⛔️
- ⛔️
- ⛔️

:sparkles: add useQuery & useMutation hooks & fetch function

---

package.json
yarn.lock

:package: install axios

---

src/styles/globals.css
tailwind.config.js

typography 설정 추가
- 사용 예시
- ⛔️
- ⛔️
- ⛔️

✨ feature: add typography setting

---

.commitlintrc.js
.husky/commit-msg
.husky/pre-commit
.lintstagedrc.json
package.json
src/pages/_app.tsx
src/stories/Button.stories.tsx
src/stories/Button.tsx
src/stories/Header.stories.tsx
src/stories/Header.tsx
src/stories/Page.stories.tsx
src/stories/Page.tsx
yarn.lock

lint-staged, commit-lint를 추가합니다.
- lint-staged ( prettier, eslint )
- commit-lint
- ⛔️
- ⛔️
- ⛔️

📦 chore: add husky, lint-staged, commit-lint

---

src/components/common/ProfileImg.tsx

profil img 컴포넌트 추가
- 사용 예시
- 결과
- #34 
- ⛔️
- ⛔️

✨ feature: add profile img

---

src/components/common/Button.tsx
src/components/common/Layout.tsx
src/components/common/Toast.tsx
src/store/components/atoms.ts
src/typings/common.d.ts
tailwind.config.js
yarn.lock

toast component 추가
- 현재 storybook에서 recoil 사용이 불가능해.. 방법을 모색중입니다.
- 슬라이드 & fade-out 애니메이션을 추가했습니다.
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: add toast component

---

src/apis/index.ts
src/components/common/CheckBox.tsx
src/components/common/Input.tsx
src/components/common/Tag.stories.tsx
src/components/common/Tag.tsx
src/components/common/Toast.tsx
src/constants/components.ts
tailwind.config.js

- 색상 팔레트를 추가했습니다.
- 컴포넌트 색상을 임의로 변경했는데, 디자인에 따라 수정해야할 부분이 있습니다.
1. ~~태그 - gray 색상 삭제 -> 작업완료~~
2. Button gray 색상 변경
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: add color palette

---

.storybook/webpack.config.js
src/components/common/NavigationBar.stories.tsx
src/components/common/NavigationBar.tsx

1. 디자인 변경에 따른 새로운 스타일을 적용하였습니다.
2. `GNB` 스토리북을 추가하였습니다.
3. `'@'` 절대 경로 설정에 따른 `Storybook` 설정을 추가하였습니다. 
- #58 
- ⛔️
- ⛔️

refactor: Fix GNB component  

---

src/components/common/Button.stories.tsx
src/components/common/CheckBox.stories.tsx
src/components/common/Input.stories.tsx
src/components/common/Tag.stories.tsx

스토리북 공통 컴포넌트 분류 추가
```diff
- title: 'Button',
+ title: 'Commons/Button',
```
- #60 
- ⛔️
- ⛔️

:recycle: refactor(storybook): Add classification common components

---

src/components/common/TextTextarea.stories.tsx
src/components/common/TextTextarea.tsx
src/components/common/Textarea.tsx

- state 관리 로직 및 handler 함수가 없는 상태이므로 추후 추가가 필요합니다.
- #63 
- ⛔️
- ⛔️

feat: talent textarea

---

src/components/common/IconAnchor.tsx
src/components/common/Popup.tsx
src/components/talentRegister/TalentRegisterCategoryHeader.tsx
src/components/talentRegister/TalentRegisterFormOne.tsx
src/components/talentRegister/TalentRegisterFormThree.tsx
src/components/talentRegister/TalentRegisterHeader.tsx
src/components/talentRegister/TalentRegisterTextRadioButtonGroup.tsx
src/hooks/useRadioGroup.ts
src/hooks/useTab.ts
src/hooks/useTalentRegisterFormDisabled.ts
src/store/components/atoms.ts
src/store/components/selectors.ts

- `useState` 사용으로 `이전` 버튼 클릭시 상태가 캐싱되지 않는 문제가 발생했어요.
- `recoil`을 사용해 문제를 해결헀어요.
```diff
- const useRadioGroup = (list: RadioUI[] | Radio[]) => {
-   const [currentSelected, setCurrentSelected] = useState<Radio>(list[0]);
+ const useRadioGroup = ({ list, inputKey }: UseRadioGroupProps) => {
+   const [currentSelected, setCurrentSelected] = useRecoilState(talentRegisterEnvironmnetAtomFamily(inputKey));
```
- 재능 게시글 작성 중단시 캐싱되고 있는 상태를 초기화 해주기위해 사용했어요.
- 동적으로 생성된 `atom`의 상태를 효율적으로 초기화 해주기 위한 방법을 찾아봤어요.
- https://github.com/facebookexperimental/Recoil/issues/387
- 관련 `issue`가 `open` 상태이며, 아직 개발 혹은 구상 단계인것으로 보여요.
- `key`를 이용하여 하나하나 `reset`하는 방식이 아닌 `RecoilRoot`를 이용한 방법
- 해당 이슈 기준 `reset`하는 근본적인 방법은 `atom`을 `default value`로 `revert`시키는 것?
- `선택 완료`가 아닌 `뒤로 가기` 버튼을 눌렀을 때 카테고리 선택 상태가 초기화 되게 만들었어요. …

feat: talent register category 3

---

public/icons/setting-arrow.svg
src/components/common/Header.tsx
src/components/common/Radio.tsx
src/hooks/usePopup.ts
src/pages/profile/index.tsx
src/pages/profile/setting.tsx
src/pages/setting/alarm.tsx
src/typings/common.d.ts

- Header 컴포넌트에 뒤로가기 추가 & 뒤로가기 안되던 이슈 수정
- 프로필 > 설정 추가 (알림 제외한 부분은 작업필요)
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: setting page pub

---

src/components/common/Card.tsx
src/components/common/CardCarousel.tsx
src/components/common/CheckBox.tsx
src/components/common/Input.tsx
src/components/common/Popup.tsx
src/components/common/Textarea.tsx
src/components/main/MainCategoryCarousel.tsx
src/components/main/MainCategoryItem.tsx
src/hooks/queries/useInfinitePostsQuery.ts
src/store/components/atoms.ts
src/typings/MainCategoryInfo.d.ts

- 프로젝트 전반적으로 type이 import 안되어 발생하는 에러를 해결합니다.
- ⛔️
- ⛔️
- ⛔️

Fix: type errors

---

src/hooks/queries/useCustomPostsQuery.ts
src/hooks/queries/useUserInfoQuery.ts
src/pages/index.tsx
src/typings/common.d.ts

메인페이지에서 userInfo, 내가 찾던 재능 API 연결
- ⛔️
- ⛔️
- ⛔️

Feat: 메인페이지에서 userInfo, 내가 찾던 재능 API

---

src/components/common/Radio.tsx
src/pages/profile/setting.tsx
src/pages/setting/alarm.tsx
src/typings/interface.d.ts

- Setting app interface 연동했습니다.
- 알람 토글 버튼 선택시, 사용자 폰 > 설정 > 핑퐁앱 으로 들어가게 됩니다.
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: Add setting interface

---

src/components/common/RadioButtonGroup.tsx
src/styles/globals.css

- `RadioButtonGroup`에서 `subLabel` 폰트 크기를 `text-b3`에서 `text-b4`로 변경했어요.
- `Button`의 `default bg color`를 `black`에서 `ping-pong-black`으로 변경했어요. 
- #101 
- ⛔️
- ⛔️

refactor: style feedback

---

src/apis/index.ts

Change baseUrl of axiosClient
- ⛔️
- ⛔️
- ⛔️

:package: chore: Change baseUrl of axiosClient

---

.husky/commit-msg
src/components/common/BottomSheetOptions.tsx
src/components/common/Layout.tsx
src/components/main/SubCategoryFilter.tsx
src/hooks/queries/useCategoriesQuery.ts
src/hooks/queries/useInfinitePostsQuery.ts
src/hooks/useBottomSheet.ts
src/pages/index.tsx
src/pages/posts/[id].tsx
src/store/components/atoms.ts
src/typings/common.d.ts
src/typings/main.d.ts

category filter API 연결
대분류 배너 클릭시 > 탭에 중분류 불러옴
중분류 선택 후 소분류 버튼 클릭 시 > 소분류 bottomsheet 열림
- ⛔️
- ⛔️
- ⛔️

Feat: category filter api

---

.github/workflows/dev-firebase-hosting-pull-request.yml
.github/workflows/prod-env.yml
next.config.js
package.json
src/pages/login.tsx
yarn.lock

:bug: fix: use dotenv

---

.github/workflows/dev-firebase-hosting-merge.yml
.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml

:sparkles: feat: Add Env file to main

---

tsconfig.json

yarn dev 시 타입에러가 있음에도 불구하고 compile 성공하는 이슈가 있어서 해당 이슈를 해결합니다.
tsconfig.json에서 잘못된 파일 include 수정
- #116 
- ⛔️
- ⛔️

:bug: fix: Remove wrong file format included at tsconfig

---

src/apis/index.ts
src/components/common/CircleCheckbox.tsx
src/hooks/queries/useNicknameMutate.ts
src/pages/nickname.tsx

- nickname page api 연동 
- 서비스 이용약관 추가
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: Add Nickname page

---

next.config.js
src/apis/index.ts
src/components/posts/PostHeaderNav.tsx
src/hooks/queries/useCategoriesQuery.ts
src/hooks/queries/useCustomPostsQuery.ts
src/hooks/queries/useInfinitePostsQuery.ts
src/hooks/queries/usePostDeleteMutate.ts
src/hooks/queries/usePostLikeMutate.ts
src/hooks/queries/usePostQuery.ts
src/hooks/queries/usePostUnlikeMutate.ts
src/hooks/queries/useReportPostMutate.ts
src/hooks/queries/useUserInfoQuery.ts
src/pages/posts/[id].tsx

게시글 상세에서 본인일때 -> 게시글 삭제 표시, API 호출
게시글 상세에서 다른사람 글일때 -> 신고 표시 
이후 내가쓴글에서 -> 게시글 상세 이동되었을때 isMyPost 에 대한 query 처리가 필요합니다. 
- ⛔️
- ⛔️
- ⛔️

Feat: report api

---

next.config.js
src/apis/index.ts
src/hooks/queries/useCategoriesQuery.ts
src/hooks/queries/useCustomPostsQuery.ts
src/hooks/queries/useInfinitePostsQuery.ts
src/hooks/queries/usePostLikeMutate.ts
src/hooks/queries/usePostQuery.ts
src/hooks/queries/usePostUnlikeMutate.ts
src/hooks/queries/useUserInfoQuery.ts

- .api 사용하던 로직이 적용되지 않은 부분이 있고 스파게티 코드를 방지해 baseURL 을 추가했습니다
- ⛔️
- ⛔️
- ⛔️

:recycle: refactor: Update baseURL

---

src/hooks/queries/useMyInfoQuery.ts
src/hooks/queries/useUserInfoQuery.ts
src/pages/main.tsx
src/pages/profile/edit/index.tsx
src/store/components/atoms.ts

- 유저 정보를 fetch해와 members/1 데이터를 수정했습니다
- dev에 배포 후 확인 가능할 것 같습니다!
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: Add user info 

---

src/components/common/Popup.tsx
src/components/common/TextRadioButtonGroup.tsx
src/components/posts/PostReportRadioGroup.tsx
src/components/talentRegister/TalentRegisterTextRadioButtonGroup.tsx
src/hooks/queries/usePostDeleteMutate.ts
src/hooks/queries/useReportPostMutate.ts
src/hooks/useRadioGroup.ts
src/pages/posts/[id].tsx

- 게시글 신고 모달, 신고 사유 라디오 그룹 추가
- useRadioGroup 이 재능등록쪽 atom value 외에 initialValue로 값을 받을 수 있도록 수정
- ⛔️
- ⛔️
- ⛔️

Feat: 게시글 상세 신고하기 기능, 신고 사유 API

---

src/components/posts/PostHeaderNav.tsx
src/components/talentRegister/TalentRegisterCategoryHeader.tsx
src/components/talentRegister/TalentRegisterFormTwo.tsx
src/components/talentRegister/TalentRegisterHeader.tsx
src/components/talentRegister/TalentRegisterTextRadioButtonGroup.tsx
src/hooks/usePopupWithBlock.ts
src/hooks/useTab.ts
src/pages/posts/[id].tsx
src/pages/profile/edit.tsx

fix: talent register

---

.github/workflows/dev-firebase-hosting-merge.yml
.github/workflows/dev-firebase-hosting-pull-request.yml
.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
firebase.json
next.config.js
package.json
src/components/common/NavigationBar.tsx
src/gen-firebase-rewrite.mjs

- Next.js 의 dynamic routing과 관련한 firebase routing 문제를 해결했습니다
- [관련 discussion](https://github.com/firebase/firebase-js-sdk/discussions/4980)
- main page에서 기존 client side 에러가 발생하는데, 해당 PR 머지 후 dev-fe 도메인에서 추가 확인 하겠습니다
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Firebase Routing issue with Nextjs

---

src/pages/index.tsx

- firebase `trailingSlash` 문제로 nickname/ 으로 리디렉션 합니다.
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Redirect to nickname/

---

next.config.js
src/apis/index.ts

- main 페이지 client-side 이슈 해결
- nextjs export / rewrite 충돌로 rewrite를 삭제했습니다!
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Remove pageNumber in infiniteQuery

---

src/components/talentRegister/TalentRegisterFormOne.tsx
src/pages/nickname.tsx

- 재능 폼 페이지에 padding을 추가했습니다
- nickname 버튼에 padding 적용 안된 부분을 수정했습니다
- ⛔️
- ⛔️
- ⛔️

:art: design: Add bottom padding

---

src/pages/posts/[id].tsx

|해결전|해결후|
|---|---|
|<img width="193" alt="image" src="https://user-images.githubusercontent.com/79739512/210170444-4bb8e5e1-9935-4e0b-8577-2560730ea879.png">|<img width="200" src="https://user-images.githubusercontent.com/79739512/210170488-ca01ddce-cc05-488e-b76d-1f77e2c5e942.png"/>|
- 게시글 신고 성공 이후 메인 페이지로 이동하는 로직을 추가 했어요
- 게시글 신고 팝업창을 띄운뒤 상태가 `reset` 되지 않는 문제를 해결했어요
- ⛔️
- ⛔️
- ⛔️

fix: design and router

---

src/apis/index.ts

- 서버에 쿠키 전송을 위해 axios 속성 추가
- ⛔️
- ⛔️
- ⛔️

:sparkles: feat: Add withCredentials for cookie

---

src/components/common/TabList.tsx
src/pages/main.tsx
src/store/components/atoms.ts

- 메인 카테고리 변경 시 midCategory 초기화
- 서브 카테고리 비어있을때 이후 filter 고장나는 이슈 해결 
- https://www.notion.so/depromeet/7e320462caa6462986600d53775319ed
- ⛔️
- ⛔️

Fix: 메인 카테고리 탭, 서브카테고리 이슈 해결

---

src/hooks/queries/useUserInfoQuery.ts

:bug: fix: Hotfix profile bug

---

src/components/common/Layout.tsx
src/components/common/Popup.tsx
src/components/talentRegister/TalentRegisterCategoryHeader.tsx
src/components/talentRegister/TalentRegisterHeader.tsx
src/hooks/usePopupWithBlock.ts
src/hooks/useTab.ts
src/pages/posts/[id].tsx
src/pages/profile/edit.tsx
src/pages/profile/edit/givenTalents/index.tsx
src/pages/profile/edit/takenTalents/index.tsx
src/pages/setting/index.tsx
src/typings/common.d.ts

- router 변경이 있을때마다 popup을 닫는 기능 추가
- ⛔️
- ⛔️
- ⛔️

feat: setPopup to null when router changed

---

src/hooks/useAuth.ts
src/pages/index.tsx

- 로그인 정보가 남아있으면 main으로 redirect
- ⛔️
- ⛔️
- ⛔️

:bug: fix: redirect to main if login status

---

src/components/common/Layout.tsx
src/hooks/useAuth.ts
src/lib/utils.ts
src/pages/dev.tsx
src/pages/index.tsx
src/pages/setting/index.tsx
src/store/components/atoms.ts

- 미로그인 상태(access_token이 있는지로 판단)에서 index.tsx 화면으로 리다이렉트 됩니다. 
- ⛔️
- ⛔️
- ⛔️

Fix: 미로그인 상태에서 index 화면으로 redirect 

---

src/pages/profile/edit.tsx
src/pages/profile/edit/givenTalents/index.tsx
src/pages/profile/edit/takenTalents/index.tsx
src/pages/profile/index.tsx

- 프로필 편집 성공 이후 `profile`로 `redirect`하게 만들었어요.
- `redirect`이후 편집 내용이 반영되지 않는 문제를 해결했어요 -> 추후 `userInfo`에 대한 리팩토링이 필요해보여요.
- 프로필 편집 중 카테고리 관련 모달에 생긴 라우팅 문제를 해결했어요.
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Fix user profile edit error

---

src/components/talentRegister/TalentRegisterFormThree.tsx
src/pages/posts/[id].tsx

fix: post delete redirect

---

src/pages/posts/[id].tsx

test: Add External Chat Link

---

src/pages/posts/[id].tsx

- 개행 문제를 해결했어요
- `이런 재능을 해요` -> `이런 재능을 원해요`로 오류를 해결했어요
|변경 전|변경 후|
|---|---|
|<img width="297" alt="image" src="https://user-images.githubusercontent.com/79739512/211257844-923c6ca6-40d0-49b9-85b9-230069615fc1.png">|<img width="299" alt="image" src="https://user-images.githubusercontent.com/79739512/211257810-8e86892b-0612-4949-a6e8-29f1e82a72c4.png">|
- ⛔️
- ⛔️
- ⛔️

fix: Fix post style issues

---

src/components/common/Toast.tsx
tailwind.config.js

토스트 디자인 가이드에 맞춰서 변경
- ⛔️
- ⛔️
- ⛔️

:art: redesign: Change toast design

---

src/components/common/Toast.tsx
src/components/profile/ProfileView.tsx
src/pages/index.tsx
tailwind.config.js

- 최초 로그인 버튼 하단 마진 추가
- 내가쓴글 > 전체보기 버튼 내가쓴글이 3개이상일때만 노출
- ⛔️
- ⛔️
- ⛔️

Fix: minor design issues

---

src/hooks/useAuth.ts
src/pages/index.tsx

use Link instead of router
- ⛔️
- ⛔️
- ⛔️

:recycle: refactor: use Link instead of router

---

src/pages/main.tsx

:art: redesign: Remove main carousel bottom margin
- ⛔️
- ⛔️
- ⛔️

:art: redesign: Remove main carousel bottom margin

---

src/components/common/NavigationBar.tsx
src/components/main/MainCategoryCarousel.tsx
src/components/main/MainCategoryItem.tsx
src/components/styles/index.tsx

fix: wrong design

---

src/pages/index.tsx

:bug: fix: Use a tag

---

src/hooks/useAuth.ts
src/pages/index.tsx

Rollback to use router
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Rollback to use router

---

src/components/profile/ProfileView.tsx
src/hooks/queries/useUserInfoQuery.ts
src/hooks/useEditProfile.ts
src/pages/profile/[id].tsx
src/pages/profile/edit.tsx
src/pages/profile/index.tsx

Fix: profile edit
- ⛔️
- ⛔️
- ⛔️

Fix: profile edit

---

src/hooks/useAuth.ts

- login시 항상 main으로 보내던 코드 제거
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Remove redirect to main always

---

src/components/common/TextBox.tsx
src/components/main/SubCategoryFilter.tsx
src/components/profile/ProfileView.tsx
src/hooks/queries/useUserInfoQuery.ts
src/hooks/useAuth.ts
src/hooks/useEditProfile.ts
src/hooks/useTab.ts
src/pages/profile/[id].tsx
src/pages/profile/edit.tsx
src/pages/profile/index.tsx

[release] v23.01.10c

---

src/hooks/useAuth.ts

:bug: fix: Fix nickname redirected

---

src/components/common/TextBox.tsx
src/pages/profile/edit.tsx

- 자기소개가 필수 값인 문제를 해결했어요.
- 자기소개 `length` `undefined`로 인해 발생하는 문제를 해결했어요
- ⛔️
- ⛔️
- ⛔️

fix: Fix profile edit submit error

---

src/components/common/TextBox.tsx
src/pages/profile/edit.tsx

[release] v23.01.10e

---

src/hooks/useNickname.ts
src/pages/nickname.tsx
src/pages/profile/edit.tsx

- 이름 -> 닉네임으로 변경
- ⛔️
- ⛔️
- ⛔️

:bug: fix: Change name to random nickname

---

src/hooks/useNickname.ts
src/pages/nickname.tsx
src/pages/profile/edit.tsx

release 230113
